### ISSUE TITLE
Revise the quarto version of the imprecision paper

### ISSUE THREAD

**Issue by rfl-urbaniak** [rfl-urbaniak/MRbook#13]

**Comment by marcellodibello** [comment]
I read the imprecision paper quarto version. I like it a lot, but here are some comments:

By the way, section numbers are missing in the pdf of the quarto version. Not sure why. 

Introduction: good
- Nothing to say

Precise v. imprecise probabilism: good, just minor things
- The description of belief inertia is not completely clear to me. Explain basic intuition (a few lines) or just add a reference. 
- The Rinard example is intriguing but I also do not understand it. Maybe add a few lines about the key intuitions?
- Is the objection to imprecise probabilism about compatibility a novel objection or did others already formulate it? Just make that clear. The objections is otherwise very interesting.

 Higher order probabilism: good, just some minor things
- In talking about expectation (p. 7), why do you say that x has to be the "objectively appropriate" degree of belief? Why not simply say that x is a degree of belief, whether appropriate or not? Why do you need that qualification? It seems controversial and I am not sure it is necessary at this point.
- For readability sake, it'd be good to show that the objections against imprecise probabilism do not apply to higher order probabilism following the same order the objections were presented earlier. It'd be good to briefly recap the objections first and then show that they do not apply here. This is just a minor expository tweak.
-  How does higher order probabilism address the "compatibility objection" against imprecise probabilism?
- I am not too impressed by the last two paragraphs of this section. Let's keep them for now, but I need to think about them.

One more question: maybe it is helpful to show why imprecise probabilities does not run into the same potential issues that higher order probabilism runs into. Let me explain. Higher order probabilism needs to explain how we conceptualize higher order probabilities (p. 9). Instead, imprecise probabilism can simply say that an agent can entertain many (compatible) probabilities. Is this why the problem does not arise for imprecise probabilism? Is this an advantage of imprecise probabilism?

The two sections about the legal examples do not work well with the rest of the paper. I am not sure what to do with them. I need to think about them. They break the flow of the argument. We need to think of how to integrate them or remove them. To be discussed.

Accuracy in the second order section: great section, but some issues below
- This section can come right after the section on higher probabilism
- The structure of the section is not completely clear to me, a bit more signposting would help, need to discuss
- The last paragraph of the section should come a bit earlier, probably before the example
- There is a lot of formal stuff here (needed), but adding intuitive explanations here and there will help the reader

Discussion
- I am not sure about the hierarchical model discussion. Need to think about this more.
- The penultimate paragraph (discussing Bradely) is very interesting. I wondering if this should go somewhere else.
- The last paragraph about semantics is also very interesting. I wonder if all the philosophical challenges about the higher order approach (semantics, conceptualization of higher order probabilities etc.) should form a separate section.

**Comment by marcellodibello** [comment]
I have an idea on how to fix the section on the two items of match evidence. The general line of argument in the paper is that higher order probabilism can address problems that imprecise probabilism fails to address (belief inertia, proper scoring rules, etc.). Now, the section on the two items of match evidence can (a) formulate a new challenge for imprecise probabilism and (b) show that this challenge can be addressed by higher order probabilism.

(a) The new challenge for imprecise probabilism is how to do updating given two pieces of evidence. Would point-wise updating on all the probability functions within a set do? It seems there will be problems with that. So the section should describe these problems. Currently the section talks about the problems with using intervals, but not with sets of probabilities.  So this needs to be reworked but it should not be too difficult to do. 

(b) The next step is then to show that higher order probabilism fares better along the lines already described in the section. So that part should be quick to do, just using existing materials.

I think (a) and (b) would make the section better integrated in the argument of the paper.
