### ISSUE TITLE
set up PR for the awareness growth work

### ISSUE THREAD

**Issue by rfl-urbaniak** [rfl-urbaniak/MRbook#35]
when ready, @marcellodibello adds reviewers' comments

**Comment by marcellodibello** [comment]
Referee: 1

Comments to the Author
The paper presents the appealing idea of using Bayesian networks to study awareness growth. I believe it needs some more work and refinements. For example, the main argument is based on the notion of "subject-matter assumptions" which is never specified or defined. Specifying this would help see the main argument with more focus (e.g. without specifying it, it remains unclear why the argument leads to the conclusion that awareness growth cannot be captured through a purely formal model). The main idea of using Bayesian networks may still be interesting.

The argumentation works well overall, although at different points the arguments could be more pointed, for example specifying more clearly what their goal is. See detailed comments for more on this. The paper is in general well-executed and organised, although again at different points it could be better organised (e.g. some explanations should come earlier -- see detailed comments for this). It introduces the novel/original idea of using Bays nets in awareness growth, although it is not entirely clear throughout the paper what the structural relations represent. It fits well with the recent growing interest in Reverse Bayesianism in formal epistemology. The conclusion it draws, that awareness growth cannot be modeled by a purely formal model, does not seem fully granted as said above.


Page 2:
11: Even if I don’t always learn the exact truth value, every time I discover a new proposition, I also gain a credence wrt to it. I may be uncertain, but that is still a credence.

17: typo, has*


Page 3:
17: typo, extend*

28: what does it mean to tackle a problem in an algorithmic manner? It makes me imagine that the author wants to provide algorithms to solve the problem, but probably that is not the case?

28: what is a subject-matter structural assumption?


Page 7:
14: what does it mean that the variables are random? It does not seem to be technically correct.  A Bayesian network typically does not involve random variables.

31: wouldn’t it be helpful to the reader to write “all the states (or values) h of H,” so to add the h? So the reader immediately understands what the h in P(H=h) refers to.

38: typo, needed*
The distinction between states and nodes becomes clear with the example. The prior description does not help at all in understanding what a state is. I think it could be made clearer.


Page 8:
24 and 36: typo friend*

17-18: what does “the formalism we are using” refer to? Does it refer to Bayesian networks or does it refer to the specific idiom used in this section?


Page 9:
2-4: I am not sure that the statement “we can compare which explanation or hypothesis makes better sense of the evidence“ expresses in words the formula (P(E = e|H = h)). The statement makes it sound like the evidence is given. It sounds like saying “given the evidence, leet’s check what is the probability that the hypothesis is H=h?”, which is (P(H = h|E = e)), differently from what the authors write.

12: initially I thought that x* should always be a new state added to H. But following up reading I think it can also be in E. Some specification of what x* could be would be welcome.

16-17: again it seems to me that the equation C is not expressed by the statement here. Rather, the formula (P(H = h|E = e)) is what the statement captures, as it says that we are checking the plausibility of the competing hypothesis given the evidence. Instead, a formula as (P(E = e|H = h)) says that given an hypothesis H=h, we want to find out how plausible it is that E=e. As this is the second time it happens, I am starting to wonder what it is that the authors want.

50-59: footnote 7 makes the case that expansion could be network changing (the discovery of Grey should be modelled by the addition of a node in the network). But then why has expansion only been defined as consisting in the addition of a state to one of the nodes in the network? This definition now seems restrictive.


Page 10:
37: what do bob, landlord, and other represent?

52: a possible fix of what? Are we fixing the challenge to Reverse Bayesianism, or Reverse Bayesianism itself?


Page 11:
2: How plausible is the principle? It may be the case that two propositions are equivalent and both basic. Imagine that Bob has Frederik as a second name. Then the propositions “Bob is singing in the shower” and “Frederik is singing in the shower” are both basics and equivalent and they should not be considered otherwise.

2: what does it mean that two propositions mean to be equivalent relative to some awareness state? I am asking this as I do not understand why the proportion of the probabilities of tenant and landlord should not remain the same if tenant is not basic. This is unclear and should be explained in the text, along with the notion of equivalence used.

13-15: why is there no obvious way to draw the line between basic and non basic propositions? A basic proposition is a formula without connectives.

22-25: what does the arrow between nodes represent now? If earlier it could represent causality, what does it represent now? Why does it make sense to represent the distinction between person and role through a network? The network represents nodes related between each other via relations that do not form cycles. So we should somehow have that it makes sense to have that person is related to role but not that role is related to person, as otherwise a cycle is formed. But why should that be? What is the intuitive understanding of the relations and this graph? It is unclear.

56-58: but why should the network be as suggested (in principle) in footnote 9? It is unclear how one constructs such networks. Why should this contain 3 nodes (in principle)?

40-41: why does this sentence only focus on Role=landlord? The node Role contains two values (landlord and tenant), and C should hold for all the values of the upstream role, so we need to check whether C holds for tenant too.


Page 12:
41: typo awareness grows* or growth*

57-58: “But arguably heads∨tails should not pick out a larger possibility space.“ It is unclear why arguably not.


Page 13:
27: typo images*

30-40: but what is the significance of this distinction between Coin and Tenant? Why is it an important asymmetry? The paper does not explain this and it is not self-evident. Explaining it would maybe also help illustrate the value of using Bayesian networks, which so far is not so clear.


Page 16:
5-6: what are seen and present/absent and good/bad exactly?

32: typo awareness grows*

36-17: what is the intuitive understanding of the arrows? Or even, what is their significance here? Are we using the arrows in our analysis? If so, how? It is not clear how the arrows, and so the network or graph is used or helps the analysis.


Page 17:
8-17: I find the explanation of the structural relationship very helpful and wish it was introduced earlier. However, edges here are taken as causal relations, whereas in a previous footnote it was said that it is not clear whether we should take them as causal or otherwise. This vagueness left some questions open to me (e.g. how to interpret the relations in the person-role graph) that cannot be answered through a causal interpretation of the edges.


Page 18:
5-6: a pointer to which subject-matter assumptions the authors are thinking would be helpful to the reader here. Also, in general it would be helpful to write at least one what is meant with ‘subject-matter assumption’.


Page 19:
2-8: it is finally nice to read how the structure of the network is used together with constraint C.

14-15: It is now clear to me that subject-matter assumptions could also be causal assumptions. It seems that much of the theory that is presented here depends on a clear definition of subject-matter assumption. As of now, they could be anything (even rather formal objects as causal relations).

22-23: why are Bayesian networks the right formal tool to model subject-matter assumptions? Could I not model them with other tools, like Kripke models? For the argument to hold, I would have to see that other formal tools do not work as well as Bayesian networks.

30-32: am I right that only now (and maybe briefly in footnote 4) it is introduced what the graph represents, and what the arrows between nodes may be taken to be? It would be *very* helpful if it was introduced *much* earlier than this, so the reader knows what she is looking at, how to interpret the structure.

**Comment by rfl-urbaniak** [comment]
PR set.

**Comment by rfl-urbaniak** [comment]
comments are copied to the discussion of that PR, let's continue our discussion over there.
